# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Mo'), (1, 'Tu'), (2, 'We'), (3, 'Th'), (4, 'Fr')]),
        ),
    ]
