# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=40)),
                ('specialties', models.ManyToManyField(related_name='disciplines', to='schedule.Specialty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=30)),
                ('term', models.PositiveSmallIntegerField()),
                ('self_education', models.BooleanField()),
                ('duration', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (4, 4), (6, 6)])),
                ('audiences_count', models.PositiveSmallIntegerField()),
                ('teachers_count', models.PositiveSmallIntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='schedule.Discipline')),
                ('previous_themes', models.ManyToManyField(related_name='_theme_previous_themes_+', to='schedule.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
