# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_discipline_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('military_rank', models.CharField(max_length=100)),
                ('work_hours_limit', models.PositiveIntegerField()),
                ('themes', models.ManyToManyField(related_name='teachers', to='schedule.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
