# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audiences',
            field=models.ManyToManyField(related_name='lessons', to='schedule.Audience'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(related_name='lessons', to='schedule.Teacher'),
        ),
    ]
