# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=40)),
                ('themes', models.ManyToManyField(related_name='audiences', to='schedule.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
