# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20170310_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='theme',
            name='previous_themes',
            field=models.ManyToManyField(to='schedule.Theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='schedule.ThemeType'),
        ),
    ]
