# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20170314_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='self_education',
        ),
        migrations.AddField(
            model_name='theme',
            name='self_education_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
