# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20170511_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='self_education',
            field=models.BooleanField(default=False),
        ),
    ]
