version: '2'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"

  web:
    depends_on:
      - celery
    build:
      context: ./schedule/
      dockerfile: Dockerfile
    environment:
      - CONTAINER_BEHAVIOUR=DJANGO
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres@db/postgres
      - SECRET_KEY=somesecretvalue
      - DJANGO_CONFIGURATION=Production
      - DJANGO_SETTINGS_MODULE=app.settings.production
      - RAVEN_DSN=http://public:secret@sentry:9000/2
    expose:
      - "8000"

  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"

  celery:
    build:
      context: ./schedule/
      dockerfile: Dockerfile
    environment:
      - CONTAINER_BEHAVIOUR=CELERY
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres@db/postgres
      - SECRET_KEY=somesecretvalue
      - DJANGO_CONFIGURATION=Production
      - DJANGO_SETTINGS_MODULE=app.settings.production
      - RAVEN_DSN=http://public:secret@sentry:9000/2
    depends_on:
      - db
      - redis

  redis:
    image: redis
    expose:
      - "6379"

  sentry:
    image: slafs/sentry
    ports:
      - "9000:9000"
    environment:
      - SENTRY_INITIAL_TEAM=schedule
      - SENTRY_INITIAL_PROJECT=schedule-backend
      - SENTRY_INITIAL_KEY=public:secret
      - SECRET_KEY=django_secret_key
      - SENTRY_URL_PREFIX=http://sentry:9000
