version: '2'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./schedule/static:/usr/src/app/static

  web:
    depends_on:
      - db
    build:
      context: ./schedule/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - SECRET_KEY=somesecretvalue
      - DJANGO_CONFIGURATION=Production
      - DJANGO_SETTINGS_MODULE=app.settings.settings
    volumes:
      - ./spa:/usr/src/spa
      - ./schedule/static:/usr/src/app/static
    expose:
      - "8000"

  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
