version: '2'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"

  web:
    depends_on:
      - db
    build:
      context: ./schedule/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - SECRET_KEY=somesecretvalue
      - DJANGO_CONFIGURATION=Production
      - DJANGO_SETTINGS_MODULE=app.settings.settings
    expose:
      - "8000"

  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
